import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { SWATCH_LIBRARY } from '../data/boconceptData';
import { X, Layers, Check, Truck } from 'lucide-react';
export const FreeSwatchesDrawer = ({ isOpen, onClose, selectedSwatches, onToggleSwatch }) => {
    const [ordered, setOrdered] = useState(false);
    const [shippingAddress, setShippingAddress] = useState({
        name: '',
        street: '',
        city: '',
        postalCode: ''
    });
    if (!isOpen)
        return null;
    const handleOrder = (e) => {
        e.preventDefault();
        setOrdered(true);
    };
    return (_jsx("div", { className: "fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex justify-end", children: _jsxs("div", { className: "bg-[#FAF8F5] w-full max-w-md h-full shadow-2xl flex flex-col justify-between border-l border-[#E6DDD4] animate-in slide-in-from-right duration-300", children: [_jsxs("div", { className: "p-6 border-b border-[#E6DDD4] flex items-center justify-between bg-[#F4EFEA]", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Layers, { className: "w-5 h-5 text-[#B0977B]" }), _jsxs("div", { children: [_jsx("h3", { className: "font-serif text-xl font-light text-[#171615]", children: "Order Free Swatches" }), _jsxs("span", { className: "text-[10px] font-mono text-gray-500 uppercase", children: [selectedSwatches.length, " / 5 Swatches Selected"] })] })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-black/10 rounded-full", children: _jsx(X, { className: "w-5 h-5 text-[#171615]" }) })] }), ordered ? (_jsxs("div", { className: "p-8 text-center space-y-6 my-auto", children: [_jsx("div", { className: "w-16 h-16 bg-[#2D3E35] text-white rounded-full flex items-center justify-center mx-auto shadow-lg", children: _jsx(Check, { className: "w-8 h-8" }) }), _jsxs("div", { children: [_jsx("h4", { className: "font-serif text-2xl text-[#171615]", children: "Free Swatch Box On Its Way!" }), _jsxs("p", { className: "text-xs text-gray-600 mt-2 font-light leading-relaxed", children: ["We are preparing your custom Danish fabric & leather sample box. Shipped free to ", _jsx("strong", { children: shippingAddress.city || 'your address' }), " in 2-4 business days."] })] }), _jsx("button", { onClick: () => { setOrdered(false); onClose(); }, className: "bg-[#171615] text-white px-8 py-3 text-xs uppercase tracking-widest font-semibold hover:bg-[#B0977B]", children: "Done" })] })) : (_jsxs("div", { className: "flex-1 overflow-y-auto p-6 space-y-6", children: [_jsx("div", { className: "bg-[#F4EFEA] p-4 border border-[#E6DDD4] text-xs text-gray-700 leading-relaxed font-light", children: "Touch and feel BoConcept fabrics in your home\u2019s natural lighting before ordering. Select up to 5 complimentary swatches." }), _jsxs("div", { className: "space-y-3", children: [_jsx("span", { className: "text-xs uppercase font-semibold tracking-wider text-[#171615]", children: "Available Material Library" }), _jsx("div", { className: "space-y-2", children: SWATCH_LIBRARY.map((swatch) => {
                                        const isSelected = selectedSwatches.some(s => s.id === swatch.id);
                                        return (_jsxs("div", { onClick: () => onToggleSwatch(swatch), className: `p-3 border flex items-center justify-between cursor-pointer transition-all ${isSelected ? 'border-[#171615] bg-[#F4EFEA]' : 'border-[#E6DDD4] hover:border-gray-400'}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "w-7 h-7 rounded-none border border-black/10 shadow-sm flex-shrink-0", style: { backgroundColor: swatch.texture } }), _jsxs("div", { children: [_jsx("h5", { className: "font-serif font-bold text-sm text-[#171615]", children: swatch.name }), _jsx("span", { className: "text-[10px] font-mono text-gray-500", children: swatch.category })] })] }), _jsx("div", { className: `w-5 h-5 rounded-full border flex items-center justify-center ${isSelected ? 'bg-[#171615] border-[#171615] text-white' : 'border-gray-300'}`, children: isSelected && _jsx(Check, { className: "w-3 h-3" }) })] }, swatch.id));
                                    }) })] }), selectedSwatches.length > 0 && (_jsxs("form", { onSubmit: handleOrder, className: "pt-4 border-t border-[#E6DDD4] space-y-3", children: [_jsx("span", { className: "text-xs uppercase font-semibold tracking-wider text-[#171615] block", children: "Delivery Address" }), _jsx("input", { type: "text", required: true, placeholder: "Full Name", value: shippingAddress.name, onChange: (e) => setShippingAddress({ ...shippingAddress, name: e.target.value }), className: "w-full p-2.5 bg-[#F4EFEA] border border-[#E6DDD4] text-xs outline-none" }), _jsx("input", { type: "text", required: true, placeholder: "Street Address", value: shippingAddress.street, onChange: (e) => setShippingAddress({ ...shippingAddress, street: e.target.value }), className: "w-full p-2.5 bg-[#F4EFEA] border border-[#E6DDD4] text-xs outline-none" }), _jsxs("div", { className: "grid grid-cols-2 gap-2", children: [_jsx("input", { type: "text", required: true, placeholder: "City", value: shippingAddress.city, onChange: (e) => setShippingAddress({ ...shippingAddress, city: e.target.value }), className: "w-full p-2.5 bg-[#F4EFEA] border border-[#E6DDD4] text-xs outline-none" }), _jsx("input", { type: "text", required: true, placeholder: "Postal Code", value: shippingAddress.postalCode, onChange: (e) => setShippingAddress({ ...shippingAddress, postalCode: e.target.value }), className: "w-full p-2.5 bg-[#F4EFEA] border border-[#E6DDD4] text-xs outline-none" })] }), _jsxs("button", { type: "submit", className: "w-full mt-4 py-3.5 bg-[#171615] text-white text-xs uppercase tracking-widest font-semibold hover:bg-[#B0977B] transition-all flex items-center justify-center gap-2", children: [_jsx(Truck, { className: "w-4 h-4" }), " Ship Free Swatch Box"] })] }))] }))] }) }));
};
