import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { PRODUCTS_CATALOG, SWATCH_LIBRARY, LEG_FINISHES } from '../data/boconceptData';
import { Check, ShoppingBag, Layers, Sparkles, SlidersHorizontal } from 'lucide-react';
export const FurnitureConfigurator = ({ onAddToCart, onOpenSwatches }) => {
    const [selectedProduct, setSelectedProduct] = useState(PRODUCTS_CATALOG[0]);
    const [selectedSwatch, setSelectedSwatch] = useState(SWATCH_LIBRARY[0]);
    const [selectedLeg, setSelectedLeg] = useState(LEG_FINISHES[0]);
    const [viewAngle, setViewAngle] = useState('front');
    const [addedAnimation, setAddedAnimation] = useState(false);
    const calculateTotalPrice = () => {
        let base = selectedProduct.basePrice * selectedSwatch.priceMultiplier;
        if (selectedLeg)
            base += selectedLeg.price;
        return Math.round(base);
    };
    const handleAddToCart = () => {
        onAddToCart(selectedProduct, selectedSwatch, selectedLeg);
        setAddedAnimation(true);
        setTimeout(() => setAddedAnimation(false), 2000);
    };
    return (_jsx("section", { id: "3d-configurator", className: "py-20 bg-[#FAF8F5] border-t border-[#E6DDD4]", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 text-xs font-mono uppercase tracking-widest text-[#B0977B] mb-2 font-semibold", children: [_jsx(SlidersHorizontal, { className: "w-4 h-4" }), "Interactive Customiser"] }), _jsx("h2", { className: "font-serif text-3xl sm:text-5xl font-light text-[#171615]", children: "Tailor Your Danish Piece" }), _jsx("p", { className: "text-[#171615]/70 font-light mt-2 max-w-xl text-sm sm:text-base", children: "Personalise fabrics, premium leathers, and handcrafted leg finishes to create a one-of-a-kind design." })] }), _jsx("div", { className: "flex flex-wrap gap-2", children: PRODUCTS_CATALOG.slice(0, 4).map((item) => (_jsx("button", { onClick: () => {
                                    setSelectedProduct(item);
                                    setSelectedSwatch(item.swatches[0] || SWATCH_LIBRARY[0]);
                                }, className: `px-4 py-2 text-xs font-semibold uppercase tracking-wider transition-all border ${selectedProduct.id === item.id
                                    ? 'bg-[#171615] text-white border-[#171615]'
                                    : 'bg-[#F4EFEA] text-[#171615] border-transparent hover:border-[#171615]'}`, children: item.name.split(' ')[0] }, item.id))) })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-8 items-start", children: [_jsxs("div", { className: "lg:col-span-7 bg-[#F4EFEA] p-6 sm:p-10 border border-[#E6DDD4] flex flex-col justify-between min-h-[480px] relative group", children: [_jsxs("div", { className: "flex items-center justify-between z-10", children: [_jsxs("div", { className: "bg-[#FAF8F5]/90 backdrop-blur-md px-3 py-1.5 border border-[#E6DDD4] text-[11px] font-mono uppercase tracking-wider text-[#171615] font-semibold flex items-center gap-2", children: [_jsx("span", { className: "w-2 h-2 rounded-full", style: { backgroundColor: selectedSwatch.texture } }), _jsx("span", { children: selectedSwatch.name })] }), _jsxs("div", { className: "flex items-center gap-1 bg-[#FAF8F5]/90 backdrop-blur-md p-1 border border-[#E6DDD4]", children: [_jsx("button", { onClick: () => setViewAngle('front'), className: `px-2.5 py-1 text-[10px] uppercase font-semibold transition-colors ${viewAngle === 'front' ? 'bg-[#171615] text-white' : 'text-[#171615] hover:bg-[#E6DDD4]'}`, children: "Front" }), _jsx("button", { onClick: () => setViewAngle('side'), className: `px-2.5 py-1 text-[10px] uppercase font-semibold transition-colors ${viewAngle === 'side' ? 'bg-[#171615] text-white' : 'text-[#171615] hover:bg-[#E6DDD4]'}`, children: "Angle" }), _jsx("button", { onClick: () => setViewAngle('detail'), className: `px-2.5 py-1 text-[10px] uppercase font-semibold transition-colors ${viewAngle === 'detail' ? 'bg-[#171615] text-white' : 'text-[#171615] hover:bg-[#E6DDD4]'}`, children: "Detail" })] })] }), _jsxs("div", { className: "relative my-6 aspect-4/3 overflow-hidden flex items-center justify-center", children: [_jsx("img", { src: viewAngle === 'front'
                                                ? selectedProduct.images[0]
                                                : viewAngle === 'side'
                                                    ? selectedProduct.images[1] || selectedProduct.images[0]
                                                    : selectedProduct.images[2] || selectedProduct.images[0], alt: selectedProduct.name, className: "w-full h-full object-cover object-center transition-all duration-500 hover:scale-105" }), _jsx("div", { className: "absolute inset-0 mix-blend-color opacity-25 pointer-events-none transition-colors duration-500", style: { backgroundColor: selectedSwatch.texture } })] }), _jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-[#E6DDD4] z-10 text-xs font-mono text-[#171615]", children: [_jsxs("div", { children: [_jsx("span", { className: "text-gray-500", children: "Designer:" }), " ", _jsx("strong", { className: "font-semibold", children: selectedProduct.designer })] }), _jsxs("div", { children: [_jsx("span", { className: "text-gray-500", children: "Dimensions:" }), " ", _jsx("strong", { className: "font-semibold", children: selectedProduct.dimensions })] }), _jsxs("button", { onClick: onOpenSwatches, className: "text-[#B0977B] underline underline-offset-4 hover:text-[#171615] font-semibold flex items-center gap-1", children: [_jsx(Layers, { className: "w-3.5 h-3.5" }), " Order Sample Swatch"] })] })] }), _jsxs("div", { className: "lg:col-span-5 bg-[#FAF8F5] p-6 sm:p-8 border border-[#E6DDD4] space-y-6", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs uppercase tracking-widest text-[#B0977B] font-semibold", children: selectedProduct.category }), _jsx("h3", { className: "font-serif text-3xl font-light text-[#171615] mt-1", children: selectedProduct.name }), _jsxs("p", { className: "text-xs text-[#171615]/70 italic mt-1 font-serif", children: ["\"", selectedProduct.tagline, "\""] })] }), _jsxs("div", { className: "space-y-3 pt-4 border-t border-[#E6DDD4]", children: [_jsxs("div", { className: "flex items-center justify-between text-xs", children: [_jsx("span", { className: "font-semibold uppercase tracking-wider text-[#171615]", children: "1. Select Upholstery Material" }), _jsx("span", { className: "text-gray-500 font-mono", children: selectedSwatch.category })] }), _jsx("div", { className: "grid grid-cols-6 gap-2", children: SWATCH_LIBRARY.map((swatch) => (_jsxs("button", { onClick: () => setSelectedSwatch(swatch), className: `aspect-square relative rounded-none p-0.5 transition-all ${selectedSwatch.id === swatch.id
                                                    ? 'ring-2 ring-[#171615] ring-offset-2'
                                                    : 'hover:scale-105'}`, title: swatch.name, children: [_jsx("div", { className: "w-full h-full border border-black/10 shadow-inner", style: { backgroundColor: swatch.texture } }), selectedSwatch.id === swatch.id && (_jsx("div", { className: "absolute inset-0 flex items-center justify-center bg-black/20", children: _jsx(Check, { className: "w-3.5 h-3.5 text-white" }) }))] }, swatch.id))) }), _jsxs("p", { className: "text-xs text-[#171615]/80 font-light bg-[#F4EFEA] p-3 border border-[#E6DDD4]", children: [_jsxs("strong", { children: [selectedSwatch.name, ":"] }), " ", selectedSwatch.description] })] }), selectedProduct.legs && selectedProduct.legs.length > 0 && (_jsxs("div", { className: "space-y-3 pt-4 border-t border-[#E6DDD4]", children: [_jsxs("div", { className: "flex items-center justify-between text-xs", children: [_jsx("span", { className: "font-semibold uppercase tracking-wider text-[#171615]", children: "2. Select Base & Leg Finish" }), _jsxs("span", { className: "text-gray-500 font-mono", children: [selectedLeg?.name, " ", selectedLeg?.price ? `(+$${selectedLeg.price})` : ''] })] }), _jsx("div", { className: "grid grid-cols-4 gap-2", children: selectedProduct.legs.map((leg) => (_jsxs("button", { onClick: () => setSelectedLeg(leg), className: `p-2 border text-center transition-all flex flex-col items-center gap-1.5 ${selectedLeg?.id === leg.id
                                                    ? 'border-[#171615] bg-[#F4EFEA]'
                                                    : 'border-[#E6DDD4] bg-[#FAF8F5] hover:border-gray-400'}`, children: [_jsx("span", { className: "w-5 h-5 rounded-full border border-black/20", style: { backgroundColor: leg.hex } }), _jsx("span", { className: "text-[10px] font-semibold text-[#171615] truncate max-w-full", children: leg.finish })] }, leg.id))) })] })), _jsxs("div", { className: "pt-6 border-t border-[#171615] space-y-4", children: [_jsxs("div", { className: "flex items-baseline justify-between", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs uppercase tracking-widest text-gray-500 font-semibold block", children: "Total Customized Price" }), _jsx("span", { className: "text-xs text-gray-500 font-mono", children: "Includes VAT & Standard Crafting" })] }), _jsxs("span", { className: "font-serif text-3xl font-normal text-[#171615]", children: ["$", calculateTotalPrice().toLocaleString()] })] }), _jsx("button", { onClick: handleAddToCart, className: `w-full py-4 text-xs uppercase tracking-widest font-semibold flex items-center justify-center gap-3 transition-all ${addedAnimation
                                                ? 'bg-[#2D3E35] text-white'
                                                : 'bg-[#171615] text-[#FAF8F5] hover:bg-[#B0977B]'}`, children: addedAnimation ? (_jsxs(_Fragment, { children: [_jsx(Check, { className: "w-4 h-4" }), _jsx("span", { children: "Added To Bag!" })] })) : (_jsxs(_Fragment, { children: [_jsx(ShoppingBag, { className: "w-4 h-4" }), _jsx("span", { children: "Add Tailored Piece to Bag" })] })) }), _jsxs("p", { className: "text-[11px] text-gray-500 text-center flex items-center justify-center gap-2", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5 text-[#B0977B]" }), "Free Danish white-glove delivery & home assembly included"] })] })] })] })] }) }));
};
