import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { ROOM_SCENES } from '../data/boconceptData';
import { PRODUCTS_CATALOG } from '../data/boconceptData';
import { Plus, Eye } from 'lucide-react';
export const RoomHotspots = ({ onQuickViewProduct }) => {
    const [activeSceneIndex, setActiveSceneIndex] = useState(0);
    const [activeHotspot, setActiveHotspot] = useState(ROOM_SCENES[0].hotspots[0]);
    const scene = ROOM_SCENES[activeSceneIndex];
    return (_jsx("section", { id: "room-hotspots", className: "py-20 bg-[#171615] text-[#FAF8F5]", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs font-mono uppercase tracking-widest text-[#C5A059] block mb-2 font-semibold", children: "Curated Interiors \u2014 Shop The Look" }), _jsx("h2", { className: "font-serif text-3xl sm:text-5xl font-light text-white", children: "Inspired Scandinavian Living" }), _jsx("p", { className: "text-white/70 font-light mt-2 max-w-xl text-sm sm:text-base", children: "Click on the hotspots to explore bespoke furnishings, material pairings, and design details in real room settings." })] }), _jsx("div", { className: "flex gap-3", children: ROOM_SCENES.map((sc, idx) => (_jsx("button", { onClick: () => {
                                    setActiveSceneIndex(idx);
                                    setActiveHotspot(sc.hotspots[0]);
                                }, className: `px-5 py-3 text-xs font-semibold uppercase tracking-widest transition-all border ${activeSceneIndex === idx
                                    ? 'bg-[#C5A059] text-white border-[#C5A059]'
                                    : 'bg-transparent text-white/80 border-white/20 hover:border-white'}`, children: sc.title }, sc.id))) })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-8 items-start w-full", children: [_jsxs("div", { className: "lg:col-span-8 relative w-full min-w-0 aspect-[16/10] sm:aspect-[16/9] overflow-hidden bg-black rounded-none border border-white/10 group", children: [_jsx("img", { src: scene.image, alt: scene.title, className: "w-full h-full object-cover object-center transition-transform duration-1000 group-hover:scale-105" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/20 pointer-events-none" }), scene.hotspots.map((hs) => {
                                    const isSelected = activeHotspot?.id === hs.id;
                                    return (_jsx("div", { style: { left: `${hs.x}%`, top: `${hs.y}%` }, className: "absolute -translate-x-1/2 -translate-y-1/2 z-20", children: _jsxs("button", { onClick: () => setActiveHotspot(hs), className: `relative w-8 h-8 rounded-full flex items-center justify-center transition-all ${isSelected
                                                ? 'bg-[#C5A059] text-white scale-125 shadow-lg shadow-[#C5A059]/50'
                                                : 'bg-white/90 text-[#171615] hover:scale-110'}`, "aria-label": `Hotspot for ${hs.title}`, children: [_jsx("span", { className: "absolute inset-0 rounded-full bg-[#C5A059] animate-ping-slow pointer-events-none" }), _jsx(Plus, { className: `w-4 h-4 transition-transform ${isSelected ? 'rotate-45' : ''}` })] }) }, hs.id));
                                }), _jsxs("div", { className: "absolute bottom-4 left-4 right-4 p-4 bg-black/70 backdrop-blur-md border border-white/10 flex items-center justify-between text-xs z-10", children: [_jsxs("div", { children: [_jsx("h4", { className: "font-serif text-lg text-white font-medium", children: scene.title }), _jsx("p", { className: "text-white/60 font-light", children: scene.subtitle })] }), _jsxs("span", { className: "hidden sm:block text-[11px] font-mono text-[#C5A059]", children: [scene.hotspots.length, " Clickable Hotspots"] })] })] }), _jsx("div", { className: "lg:col-span-4 w-full min-w-0 bg-[#232220] p-6 border border-white/10 flex flex-col justify-between", children: activeHotspot ? (_jsxs("div", { className: "space-y-6 animate-in fade-in duration-300", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-white/10 pb-4", children: [_jsx("span", { className: "text-[10px] font-mono uppercase tracking-widest text-[#C5A059]", children: "Selected Piece" }), _jsx("span", { className: "text-xs font-mono text-white/50", children: "Hotspot Tagged" })] }), _jsx("div", { className: "aspect-[4/3] w-full overflow-hidden bg-black/40 border border-white/10", children: _jsx("img", { src: activeHotspot.image, alt: activeHotspot.title, className: "w-full h-full object-cover" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-serif text-2xl font-light text-white", children: activeHotspot.title }), _jsxs("p", { className: "font-serif text-xl text-[#C5A059] mt-1 font-semibold", children: ["$", activeHotspot.price.toLocaleString()] }), _jsx("p", { className: "text-xs text-white/70 font-light mt-3 leading-relaxed", children: activeHotspot.description })] }), _jsx("div", { className: "space-y-3 pt-4 border-t border-white/10", children: _jsxs("button", { onClick: () => {
                                                const fullProduct = PRODUCTS_CATALOG.find(p => p.id === activeHotspot.productId);
                                                if (fullProduct)
                                                    onQuickViewProduct(fullProduct);
                                            }, className: "w-full py-3.5 bg-[#FAF8F5] text-[#171615] hover:bg-[#C5A059] hover:text-white transition-all text-xs font-semibold uppercase tracking-widest flex items-center justify-center gap-2", children: [_jsx(Eye, { className: "w-4 h-4" }), _jsx("span", { children: "View Specifications & Customise" })] }) })] })) : (_jsxs("div", { className: "h-full flex flex-col items-center justify-center text-center py-12 text-white/50 space-y-3", children: [_jsx(Plus, { className: "w-8 h-8 text-[#C5A059] animate-bounce" }), _jsx("p", { className: "text-sm font-serif italic", children: "Select any hotspot pin on the room image to view product details." })] })) })] })] }) }));
};
