import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { STORES_LOCATIONS } from '../data/boconceptData';
import { MapPin, X, Phone, Clock, Sparkles } from 'lucide-react';
export const StoreLocatorModal = ({ isOpen, onClose, onOpenConsultation }) => {
    if (!isOpen)
        return null;
    const [selectedStore, setSelectedStore] = useState(STORES_LOCATIONS[0]);
    return (_jsx("div", { className: "fixed inset-0 z-50 bg-black/70 backdrop-blur-md flex items-center justify-center p-4", children: _jsxs("div", { className: "bg-[#FAF8F5] w-full max-w-3xl rounded-none border border-[#E6DDD4] shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200", children: [_jsxs("div", { className: "p-6 border-b border-[#E6DDD4] flex items-center justify-between bg-[#171615] text-white", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(MapPin, { className: "w-5 h-5 text-[#C5A059]" }), _jsxs("div", { children: [_jsx("span", { className: "text-[10px] font-mono uppercase tracking-widest text-[#C5A059] block", children: "Flagship Showrooms" }), _jsx("h3", { className: "font-serif text-2xl font-light", children: "Find a K\u00D8BENHAVN Store" })] })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-white/10 rounded-full text-white", children: _jsx(X, { className: "w-5 h-5" }) })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-12", children: [_jsx("div", { className: "md:col-span-5 border-r border-[#E6DDD4] bg-[#F4EFEA] p-4 space-y-2 max-h-[400px] overflow-y-auto", children: STORES_LOCATIONS.map((store) => (_jsxs("button", { onClick: () => setSelectedStore(store), className: `w-full p-4 text-left border transition-all ${selectedStore.city === store.city
                                    ? 'border-[#171615] bg-[#FAF8F5] shadow-sm'
                                    : 'border-transparent hover:bg-black/5'}`, children: [_jsx("h4", { className: "font-serif font-bold text-base text-[#171615]", children: store.city }), _jsx("p", { className: "text-xs text-gray-600 font-light mt-1", children: store.address })] }, store.city))) }), _jsxs("div", { className: "md:col-span-7 p-6 sm:p-8 space-y-6 flex flex-col justify-between", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs font-mono uppercase text-[#B0977B] tracking-widest font-semibold block", children: "Store Details" }), _jsx("h3", { className: "font-serif text-3xl font-light text-[#171615] mt-1", children: selectedStore.city })] }), _jsxs("div", { className: "space-y-3 text-xs text-gray-700 font-light pt-3 border-t border-[#E6DDD4]", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx(MapPin, { className: "w-4 h-4 text-[#B0977B] flex-shrink-0 mt-0.5" }), _jsx("span", { children: selectedStore.address })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Phone, { className: "w-4 h-4 text-[#B0977B] flex-shrink-0" }), _jsx("span", { children: selectedStore.phone })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Clock, { className: "w-4 h-4 text-[#B0977B] flex-shrink-0" }), _jsx("span", { children: selectedStore.hours })] })] })] }), _jsxs("div", { className: "aspect-16/9 bg-[#E6DDD4] relative overflow-hidden border border-[#E6DDD4] flex items-center justify-center", children: [_jsx("img", { src: selectedStore.image || "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", alt: `${selectedStore.city} Showroom`, className: "w-full h-full object-cover opacity-90 transition-all duration-500" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent flex items-end p-4", children: _jsxs("span", { className: "bg-[#171615] text-white px-3 py-1.5 text-xs uppercase tracking-widest font-semibold flex items-center gap-2 shadow-lg", children: [_jsx(MapPin, { className: "w-4 h-4 text-[#C5A059]" }), " ", selectedStore.city] }) })] }), _jsxs("button", { onClick: () => { onClose(); onOpenConsultation(); }, className: "w-full py-3.5 bg-[#171615] text-white text-xs uppercase tracking-widest font-semibold hover:bg-[#B0977B] transition-all flex items-center justify-center gap-2", children: [_jsx(Sparkles, { className: "w-4 h-4 text-[#C5A059]" }), "Book In-Store Styling Appointment"] })] })] })] }) }));
};
